name: PyTest
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: pytest - OS ${{ matrix.os }} - Python ${{ matrix.python-version }} - pandas ${{ matrix.pandas-version }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]
        # Remove Python 3.7.9 on 27 Jun 2023: https://endoflife.date/python
        python-version: ["3.7.9", "3.8.10", "3.9.13", "3.10.8"]
        pandas-version: ["1.0.5", "1.1.5", "1.2.5", "1.3.5", "1.4.3", "2.0", ""]

        exclude:
          # see https://github.com/nalepae/pandarallel/pull/211#issuecomment-1362647674
          - python-version: "3.8.10"
            pandas-version: "1.0.5"
          # Pandas 2.0 requires Python >= 3.8
          - python-version: "3.7.9"
            pandas-version: "2.0"
          # Pandas 1.4.3 requires Python >= 3.8
          - python-version: "3.7.9"
            pandas-version: "1.4.3"
          # Pandas 1.0.5 has to be fully rebuilt with Python >= 3.9.13 (taking > 10 min)
          - python-version: "3.9.13"
            pandas-version: "1.0.5"
          # Pandas 1.0.5 has to be fully rebuilt with Python >= 3.9.13 (taking > 10 min)
          - python-version: "3.10.8"
            pandas-version: "1.0.5"
          # Pandas 1.1.5 has to be fully rebuilt with Python >= 3.10.5 (taking > 10 min)
          - python-version: "3.10.8"
            pandas-version: "1.1.5"
          # Pandas 1.2.5 has to be fully rebuilt with Python >= 3.10.5 (taking > 10 min)
          - python-version: "3.10.8"
            pandas-version: "1.2.5"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Replace with specific pandas version (${{ matrix.pandas-version }})
      if: ${{ matrix.pandas-version }}
      run: pip install pandas==${{ matrix.pandas-version }}
    - name: Test with pytest
      run: |
        pytest --cov=pandarallel
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
